openapi: 3.0.3
info:
  title: User Service
  description: |
    Aggregator Service is a service that aggregates data from other data sources. It aims to provide a near-realtime data to the client. # Authentication <!-- ReDoc-Inject: <security-definitions> -->
  version: 0.1.0
  contact:
    email: kien.nguyen@your.rentals
    name: Kien Nguyen
servers:
  - url: 'https://localhost:8080'
    description: Local
  - url: 'https://guest-gateway-dev.your.rentals'
    description: Development
  - url: 'https://guest-gateway.your.rentals'
    description: Production
security:
  - bearerAuth: []
tags:
  - name: Inquiry
  - name: Inquiry V2
  - name: User
paths:
  '/users/{userId}/device-logs':
    post:
      tags:
        - User
      summary: Store user's information after login
      description: |
        Store user's information after login
      operationId: storeLoginLogs
      parameters:
        - schema:
            type: string
          name: userId
          in: path
          required: true
          description: User ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - ip
                - action
                - logTypes
                - deviceId
              properties:
                userAgent:
                  type: string
                ip:
                  type: string
                action:
                  type: string
                  description: |
                    Follow the above value(In this case this value should be: login)
                  enum:
                    - login
                logTypes:
                  type: string
                  description: |
                    Follow the above value(In this case this value should be:normal)
                  enum:
                    - normal
                    - system
                country:
                  type: string
                  description: |
                    User's country
                deviceId:
                  type: string
                  description: |
                    The information of device
      responses:
        '200':
          description: OK
  /user/messages/inquiry:
    post:
      summary: Create Inquiry
      operationId: createInquiry
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conversation-response.v1'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conversation-response.v1'
      description:
        Receive inquiry request from sales channels via gateway forward request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                salesChannelId:
                  type: string
                  description: 'Sales channel ID '
                  enum:
                    - PMDR
                    - AIRB
                    - BOCM
                  default: PMDR
                salesChannelConversationId:
                  type: string
                  description:
                    'Sales channel conversation id, required if sale channel is
                    AIRB'
                salesChannelInquiryId:
                  type: string
                  description:
                    Required for type REQUEST_TO_BOOK of BOCM as salesChannelId,
                    this BOCM's reference inquiry id can not be duplicate
                salesChannelMessageId:
                  type: string
                  description: Sales channel message id
                listingId:
                  type: integer
                  minimum: 0
                  exclusiveMinimum: true
                  example: 344519
                  description: Listing ID
                from:
                  type: string
                  example: '2023-07-04'
                  description: Check-in date
                to:
                  type: string
                  description: Check-out date
                  example: '2023-04-14'
                adults:
                  type: integer
                  exclusiveMinimum: true
                  minimum: 0
                  description: Number of adults
                children:
                  type: integer
                  description: Number of children
                guestFirstname:
                  type: string
                  description: Guest first name
                guestLastname:
                  type: string
                  description: Guest last name. Required if PMDR
                guestEmail:
                  type: string
                  description: 'Guest email, required if PMDR'
                message:
                  type: string
                  description: Message of the guest
                  maxLength: 2000
                phone:
                  type: string
                  description: Phone number
                  example: (+84)915678321
                occasion:
                  type: string
                  description: Occasion
                  example: Example occasion
                company:
                  type: string
                  example: Your Rentals
                  description: Guest company
                type:
                  type: string
                  enum:
                    - GENERAL_INQUIRY
                    - REQUEST_TO_BOOK
                  description: |
                    Inquiry Type, default is GENERAL_INQUIRY
                  default: GENERAL_INQUIRY
                cancellationPolicyId:
                  type: string
                  description:
                    Required for type REQUEST_TO_BOOK of BOCM as salesChannelId
                  enum:
                    - Free7
                    - Free14
                    - Free30
                    - SuperFlexible
                    - Flexible
                    - Moderate
                    - Strict
                    - NonRefundable
              required:
                - salesChannelId
                - listingId
                - message
      tags:
        - Inquiry
  /v2/inquiries/{inquiryId}/accept-request-to-book:
    parameters:
      - schema:
          type: string
        name: inquiryId
        in: path
        required: true
        description: Inquiry ID
    post:
      summary: Accept a request to book inquiry
      operationId: acceptRequestToBookInquiry
      responses:
        '200':
          description: OK
        '400':
          description: Bad request exception
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    description: The HTTP status code
                  message:
                    type: string
                    description: The error message
              examples:
                Inquiry is not of type request to book:
                  value:
                    statusCode: 400
                    message: Inquiry is not of type request to book
                Inquiry has expired and cannot be accepted:
                  value:
                    statusCode: 400
                    message: Inquiry has expired and cannot be accepted
      description: Accept a request to book inquiry
      tags:
        - Inquiry V2
  /v2/inquiries/{inquiryId}/decline-request-to-book:
    parameters:
      - schema:
          type: string
        name: inquiryId
        in: path
        required: true
        description: Inquiry ID
    post:
      summary: Decline a request to book inquiry
      operationId: declineRequestToBookInquiry
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - reason
                properties:
                  reason:
                    type: string
                    description: |-
                      Reason of the decline request:
                      | Value | Description |
                      | - | - |
                      | DATES_NOT_AVAILABLE | The requested dates are not available |
                      | POLICY_DONT_FIT_NEEDS | House rules or policies don't match the guest's needs |
                      | OUTSIDE_HOURS_CHECKIN | The request's check-in time does not suit my availability |
                      | MISSING_INFORMATION | Trip or account details are in-complete |
                      | NOT_COMFORTABLE | I'm not comfortable accepting this request |
                    enum:
                      - DATES_NOT_AVAILABLE
                      - POLICY_DONT_FIT_NEEDS
                      - OUTSIDE_HOURS_CHECKIN
                      - MISSING_INFORMATION
                      - NOT_COMFORTABLE
                  notes:
                    type: string
                    description:
                      Notes for PM's reason. Required if the reason is
                      NOT_COMFORTABLE
              examples:
                Normal reason cases:
                  value:
                    reason: DATES_NOT_AVAILABLE
                Not comfortable case:
                  value:
                    reason: NOT_COMFORTABLE
                    notes: I'm going to schedule a maintenance on this house
        '400':
          description: Bad request exception
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    description: The HTTP status code
                  message:
                    type: string
                    description: The error message
              examples:
                Inquiry is not of type request to book:
                  value:
                    statusCode: 400
                    message: Inquiry is not of type request to book
                Inquiry has expired and cannot be declined:
                  value:
                    statusCode: 400
                    message: Inquiry has expired and cannot be declined
      description: Decline a request to book inquiry
      tags:
        - Inquiry V2
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    conversation-response.v1:
      type: object
      x-examples:
        Example 1:
          accountId: fb0cbf81-5524-4c0e-8b13-a7a5d15efa06
          state: unread
          inquiryId: d4d64d52-70b2-4f05-ba33-e36d6658f066
          checkInAt: '2023-07-04T00:00:00.000Z'
          guestName: hoan le
          lastActivityAt: '2023-07-03T09:12:23.638Z'
          listingId: 344519
          salesChannelId: BOCM
          id: c3b3feab-485b-4fe3-99c4-fd9ca572827a
          createdAt: '2023-07-03T09:12:23.647Z'
      properties:
        id:
          type: string
          description: Id of conversation
        accountId:
          type: string
          description: Account ID
        state:
          type: string
          description: State of the conversation
        inquiryId:
          type: string
          description: Inquiry ID
        checkInAt:
          type: string
          description: Check in timestamp
        guestName:
          type: string
          description: Guest name
        lastActivityAt:
          type: string
          description: last activity time stamp
        listingId:
          type: integer
          description: Listing ID
        salesChannelId:
          type: string
          description: Sales Channel ID
        createdAt:
          type: string
          description: Created timestamp
x-tagGroups: []
